In [1]:
%matplotlib inline

In [2]:
import numpy as np
import scipy as sp
import sklearn as sk

In [3]:
import numpy as np
import time
from numpy.linalg import eigvals
results = []
def run_experiment(niter=100): 
    K = 100
    for _ in xrange(niter):
        mat = np.random.randn(K, K)
        max_eigenvalue = np.abs(eigvals(mat)).max() 
        results.append(max_eigenvalue)
    return results
start = time.time()
some_results = run_experiment()
print 'Largest one we saw: %s' % np.max(some_results)
print (time.time() - start)

Largest one we saw: 11.6363823356
0.590433835983


In [18]:
!python -m cProfile -s cumulative cprof_example.py

Largest one we saw: 10.8813511717
         11765 function calls (11644 primitive calls) in 0.072 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.021    0.007    0.089    0.030 __init__.py:1(<module>)
        1    0.000    0.000    0.072    0.072 cprof_example.py:1(<module>)
        1    0.002    0.002    0.065    0.065 __init__.py:106(<module>)
        1    0.000    0.000    0.049    0.049 add_newdocs.py:10(<module>)
        1    0.000    0.000    0.041    0.041 type_check.py:3(<module>)
        1    0.000    0.000    0.015    0.015 __init__.py:7(<module>)
        1    0.000    0.000    0.008    0.008 decorators.py:15(<module>)
        1    0.002    0.002    0.008    0.008 utils.py:4(<module>)
        2    0.001    0.001    0.007    0.003 __init__.py:45(<module>)
        1    0.006    0.006    0.007    0.007 __init__.py:88(<module>)
        1    0.000    0.000    0.006    0.006 cprof_example.py:5(run_experi

In [21]:
class Greeter:
    def __init__(self, msg):
        self.msg = msg
    def __repr__(self):
        return "Message : %s" % self.msg

In [22]:
x = Greeter("I am grateful")
x

Message : I am grateful

In [24]:
data = [1,6.7,3,2.5]
arr1 = np.array(data)
print arr1

[ 1.   6.7  3.   2.5]


In [64]:
data = np.random.randn(7,4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [94]:
arr = np.empty((8,4))
for i in range(8):
    arr[i,:] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [99]:
rand_arr = np.random.randn(4,3)
rand_arr

array([[-0.89213371,  0.89853129, -0.77859847],
       [ 0.13919284, -0.61229128, -1.4298755 ],
       [-0.26943731, -0.98894912,  0.62258565],
       [-0.58963184,  0.72409058,  1.62164625]])

In [112]:
x = np.random.randn(8)
y = np.random.randn(8)
print x
print y
print np.max(x)
print np.max(y)
print np.maximum(x,y)

[  6.20301650e-01   3.81451833e-04  -3.65683122e-02  -4.75295628e-01
   5.16016378e-01   1.13203483e+00  -4.67928285e-01   9.76955991e-01]
[ 1.70974641 -0.26510964  0.47380398  0.52664989 -0.99866956 -0.31725434
 -0.12221691 -1.04265385]
1.1320348333
1.70974640505
[  1.70974641e+00   3.81451833e-04   4.73803982e-01   5.26649893e-01
   5.16016378e-01   1.13203483e+00  -1.22216912e-01   9.76955991e-01]


In [124]:
a = np.arange(-5,5,0.1)
print a
xs,ys = np.meshgrid(a,a)

[ -5.00000000e+00  -4.90000000e+00  -4.80000000e+00  -4.70000000e+00
  -4.60000000e+00  -4.50000000e+00  -4.40000000e+00  -4.30000000e+00
  -4.20000000e+00  -4.10000000e+00  -4.00000000e+00  -3.90000000e+00
  -3.80000000e+00  -3.70000000e+00  -3.60000000e+00  -3.50000000e+00
  -3.40000000e+00  -3.30000000e+00  -3.20000000e+00  -3.10000000e+00
  -3.00000000e+00  -2.90000000e+00  -2.80000000e+00  -2.70000000e+00
  -2.60000000e+00  -2.50000000e+00  -2.40000000e+00  -2.30000000e+00
  -2.20000000e+00  -2.10000000e+00  -2.00000000e+00  -1.90000000e+00
  -1.80000000e+00  -1.70000000e+00  -1.60000000e+00  -1.50000000e+00
  -1.40000000e+00  -1.30000000e+00  -1.20000000e+00  -1.10000000e+00
  -1.00000000e+00  -9.00000000e-01  -8.00000000e-01  -7.00000000e-01
  -6.00000000e-01  -5.00000000e-01  -4.00000000e-01  -3.00000000e-01
  -2.00000000e-01  -1.00000000e-01  -1.77635684e-14   1.00000000e-01
   2.00000000e-01   3.00000000e-01   4.00000000e-01   5.00000000e-01
   6.00000000e-01   7.00000000e-01

In [127]:
z = (xs**2 + ys**2)
print z

[[ 50.    49.01  48.04 ...,  47.09  48.04  49.01]
 [ 49.01  48.02  47.05 ...,  46.1   47.05  48.02]
 [ 48.04  47.05  46.08 ...,  45.13  46.08  47.05]
 ..., 
 [ 47.09  46.1   45.13 ...,  44.18  45.13  46.1 ]
 [ 48.04  47.05  46.08 ...,  45.13  46.08  47.05]
 [ 49.01  48.02  47.05 ...,  46.1   47.05  48.02]]


In [134]:
xarr = np.array([1,2,3,4,5])
yarr = np.array([6,7,8,9,10])
condn = np.array([True, False, True, False, False])
result = np.where(condn,xarr,yarr)
result

array([ 1,  7,  3,  9, 10])

In [11]:
from numpy.linalg import inv, qr
a = np.random.randn(4,4)
print a
print ""
print np.sort(a)
print ""
print np.sort(a, axis=0)
# Check how the mutiplication of transpose of a matrix and the matrix gives a s a result
print ""
b = np.dot(inv(a) ,a)
print b

[[ 1.10204963  0.9562473  -0.66371926 -0.00193939]
 [-1.16356839 -0.21225506  0.63615842 -1.04159213]
 [ 0.78918603  1.78833943  0.3669307  -0.27295407]
 [ 1.04304393 -0.19494739 -0.08094318 -0.03074654]]

[[-0.66371926 -0.00193939  0.9562473   1.10204963]
 [-1.16356839 -1.04159213 -0.21225506  0.63615842]
 [-0.27295407  0.3669307   0.78918603  1.78833943]
 [-0.19494739 -0.08094318 -0.03074654  1.04304393]]

[[-1.16356839 -0.21225506 -0.66371926 -1.04159213]
 [ 0.78918603 -0.19494739 -0.08094318 -0.27295407]
 [ 1.04304393  0.9562473   0.3669307  -0.03074654]
 [ 1.10204963  1.78833943  0.63615842 -0.00193939]]

[[  1.00000000e+00  -1.11022302e-16  -6.93889390e-17  -1.38777878e-16]
 [  0.00000000e+00   1.00000000e+00   4.85722573e-17   1.35308431e-16]
 [ -3.33066907e-16   0.00000000e+00   1.00000000e+00  -4.78783679e-16]
 [ -2.22044605e-16  -4.16333634e-17   3.46944695e-17   1.00000000e+00]]


In [177]:
print names
print np.unique(names)
print set(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
['Bob' 'Joe' 'Will']
set(['Will', 'Bob', 'Joe'])


In [180]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[6,23], [-1,7], [8,9]])
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [184]:
print np.ones(3)
np.dot(x, np.ones(3))

[ 1.  1.  1.]


array([  6.,  15.])

In [12]:
a.dot(inv(a))

array([[  1.00000000e+00,  -3.40005801e-16,   2.35326082e-16,
         -4.42354486e-17],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  5.55111512e-17,   0.00000000e+00,   1.00000000e+00,
          5.55111512e-17],
       [  1.80411242e-16,   1.66533454e-16,  -1.47451495e-16,
          1.00000000e+00]])